// development/frontend-react/src/components/Hero.tsx
import React from 'react';

interface Props {
    color: string;
}


export const Hero: React.FunctionComponent<Props> = ({ color, children }) => (
    <section className={`hero is-fullheight is-bold ${color}`}>
        <div className='hero-body'>
            <div className='container'>
                {children}
            </div>
        </div>
    </section>
);

// development/frontend/src/components/Hero.vue
<template>
    <section :class="['hero', 'is-fullheight', 'is-bold', color]" v>
        <div class="hero-body">
            <div class="container">
                <slot></slot>
            </div>
        </div>
    </section>
</template>
<script>
export default {
    props: {
        color: String
    }
}
</script>
